# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6553e6c7aafcd6da2824aa62f5925ef0256c950a5e1b8a363d22eca750e81117489205ceb309bbd4ead42bf9995b8ecdc306966facda9ddf522b5894f7f45567

test:
  secret_key_base: c68f7d57942f00fe13f858e70617cd491aa72b0722835d5401665854567010fc30c3945d7a8d7b5c8f25b89674270219e070cd64e9aa6d421666c326e82d5f4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
